source 'https://github.com/CocoaPods/Specs.git'

target 'CGLMediaPicker', :exclusive => true do
  pod "CGLMediaPicker", :path => "../"
end

target 'Tests', :exclusive => true do
  pod "CGLMediaPicker", :path => "../"

  
end
